---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1","kind":"Kustomization","metadata":{"annotations":{},"name":"monitoring-controllers","namespace":"flux-system"},"spec":{"interval":"10m","path":"./monitoring/controllers","prune":true,"sourceRef":{"kind":"GitRepository","name":"monitoring-example"},"timeout":"10m","wait":true}}
    reconcile.fluxcd.io/requestedAt: "2026-01-15T10:44:52.983418247Z"
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./monitoring/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-example
  timeout: 10m0s
