---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1","kind":"Kustomization","metadata":{"annotations":{},"name":"monitoring-configs","namespace":"flux-system"},"spec":{"dependsOn":[{"name":"monitoring-controllers"}],"interval":"10m","path":"./monitoring/configs","prune":true,"sourceRef":{"kind":"GitRepository","name":"monitoring-example"},"timeout":"10m","wait":true}}
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: monitoring-controllers
  interval: 10m0s
  path: ./monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-example
  timeout: 10m0s
  wait: true
